version: 0.2
phases:
  install:
    commands:
      - echo "Installing zip"
      - yum install -y zip
  build:
    commands:
      - zip -r php-sample-app.zip .
artifacts:
  files:
    - php-sample-app.zip
