version: 0.2

phases:
  pre_build:
    commands:
      - echo "Authenticating to Docker Hub..."
      - docker login -u ajith3010 -p Chettiyar@9769
      - echo "Authenticating to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 499250238649.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t php-app-repo .
      - echo "Tagging the Docker image..."
      - docker tag php-app-repo:latest 499250238649.dkr.ecr.us-east-1.amazonaws.com/php-app-repo:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 499250238649.dkr.ecr.us-east-1.amazonaws.com/php-app-repo:latest
      - echo "Writing imagedefinitions.json file..."
      - printf '[{"name":"php-container","imageUri":"499250238649.dkr.ecr.us-east-1.amazonaws.com/php-app-repo:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
